function ima=imaqq(X)
MSB=bitshift(bitshift(X,-4),4);
LSB = X-bitshift(bitshift(X,-4),4); 
convert_MSB=bitshift(MSB,-4);
compressLSB=compression(LSB);
compressMSB=compression(convert_MSB);
Chao=Chaotic_sequance(90);
MSB_P=permat(compressMSB,Chao,60,50);
LSB_P=permat(compressLSB,Chao,60,50);
LSBSbox=sbox_of_order_16(12,4,8,13,19);
MSBSbox=sbox_of_order_16(12,4,8,13,25);
LSBXOR=xo_r(LSB_P,Chao);
MSBXOR=xo_r(MSB_P,Chao);
sub_LSB=substitute(LSBXOR,LSBSbox);
sub_MSB=substitute(MSBXOR,LSB_P);
MSB_Ex=double(bitshift(sub_MSB-bitshift(bitshift(sub_MSB,-4),4),4));
Image=uint8(double(MSB_Ex+sub_LSB));
Image=exo_r(Image,Chao);
ima=Image;